export const metadata = {
     title: "Sound Cloud",
     description: "Generated by Next.js",
};

export default function RootLayout({
     children,
}: {
     children: React.ReactNode;
}) {
     return (
          <>
               {children}
          </>
     );
}
